version: '3'

services:
  telegram-logs:
    build: .
    network_mode: "host"
    ports:
      - "127.0.0.1:$TELEGRAM_BOT_PORT:2025"
    entrypoint: ["python3", "main.py"]
    healthcheck:
      test: "exit 0"
